### ISSUE TITLE
Chompy should delete old videos

### ISSUE THREAD

**Issue by Hebo** [Hebo/chompy#2]
Chompy doesn't clean up downloaded videos. It should.

Probably sufficient to allow users to specify a maximum directory size, and delete videos when near that limit.

**Implementation notes:**
- Allow user to set size in MB
- If size on startup is over the limit, ask the user to delete manually so we don't inadvertently delete their files
- Run deletions after every successful download job
- (?) Will yt-dl re-download deleted files from playlists

**Comment by Acrom11** [comment]
1+

**Comment by Hebo** [comment]
Likely will get to this after #3 , feel free to add any specific needs.
