### ISSUE TITLE
Set title on Video list page

### ISSUE THREAD

**Issue by Hebo** [Hebo/chompy#8]
Currently missing a <title> on `/videos`, add one. Maybe even a favicon one day...

**Comment by cp-urvi-k** [comment]
@Hebo What Title you want to display there? `Chompy`??

**Comment by Hebo** [comment]
Sure! Something like "Videos - Chompy" should suffice.

**Comment by cp-urvi-k** [comment]
@Hebo Please review the changes - https://github.com/Hebo/chompy/pull/11

**Comment by cp-urvi-k** [comment]
@Hebo it's done!
Please review: https://github.com/Hebo/chompy/pull/12

**Comment by Hebo** [comment]
Thank you!
